---
    - name: Ensure apt cache is up to date
      apt:
        update_cache: true

    - name: Install prerequisite packages
      apt:
        name:
          - docker.io
          - docker-compose
          
    - name: Add the domain name to DuckDNS
      tags: duckdns
      ansible.builtin.uri:
        url: "https://www.duckdns.org/update?domains={{ DOMAIN_NAME }}&token={{ TOKEN }}"
        method: GET
        
