---
- name: copy dir to droplet && install dependencies
  hosts: localhost
  gather_facts: no
  vars:
    droplet_name: my-new-droplet  # Replace this with your droplet's name
  tasks:
    - name: read droplet IP address from file
      slurp:
        src: "./droplet_ip.txt"
      register: slurped_content

    - name: set droplet IP address as a variable
      set_fact:
        droplet_ip: "{{ slurped_content.content | b64decode }}"

    - name: wait for ssh to be available
      wait_for:
        host: "{{ droplet_ip }}"
        port: 22
        delay: 10
        timeout: 300
        state: started
        
    - name: install docker on droplet
      ansible.builtin.apt:
        name: docker.io
        state: present
      delegate_to: "{{ slurped_content.content | b64decode }}"
      become: yes

    - name: install docker-compose on droplet
      ansible.builtin.apt:
        name: docker-compose
        state: present
      delegate_to: "{{ slurped_content.content | b64decode }}"
      become: yes

    - name: install make on droplet
      ansible.builtin.apt:
        name: make
        state: present
      delegate_to: "{{ slurped_content.content | b64decode }}"
      become: yes

    - name: copy dir to droplet
      ansible.posix.synchronize:
        mode: push
        src: "../inception"
        dest: "/home/ubuntu/"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=venv"
      delegate_to: "{{ slurped_content.content | b64decode }}"
      become: yes

    - name: run make on droplet
      ansible.builtin.command:
        cmd: make
      args:
        chdir: "/home/ubuntu/inception"
      delegate_to: "{{ slurped_content.content | b64decode }}"
      become: yes 