- name: Create a DigitalOcean Droplet
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a DigitalOcean Droplet
      community.digitalocean.digital_ocean_droplet:
        name: my-new-droplet
        state: present
        api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"  # Use the environment variable
        size: s-1vcpu-1gb
        image: ubuntu-20-04-x64
        region: nyc1
        ssh_keys:
          - "{{ lookup('env', 'DO_SSH_KEY_ID') }}"  # Use the environment variable for SSH key ID
        tags:
          - "web"
        wait: yes
      register: do_droplet