---
- name: Create a DigitalOcean Droplet
  hosts: localhost
  gather_facts: no
  vars:
    droplet_name: "my-new-droplet"  # Replace this with your droplet's name
    droplet_size: "s-1vcpu-1gb"
    droplet_image: "ubuntu-20-04-x64"
    droplet_region: "nyc1"
    droplet_tags: ["web"]
  
  tasks:
    - name: Create a DigitalOcean Droplet
      community.digitalocean.digital_ocean_droplet:
        name: "{{ droplet_name }}"
        state: present
        api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"  # Use the environment variable
        size: "{{ droplet_size }}"
        image: "{{ droplet_image }}"
        region: "{{ droplet_region }}"
        ssh_keys:
          - "{{ lookup('env', 'DO_SSH_KEY_ID') }}"  # Use the environment variable for SSH key ID
        tags: "{{ droplet_tags }}"
        wait: yes
        wait_timeout: 100  # Increased timeout to 5 minutes
      register: do_droplet

    - name: Display the Droplet IP address
      debug:
        var: do_droplet.data.droplet.networks.v4[0].ip_address
    
    - name: copy ip_address
      copy:
        content: "{{ do_droplet.data.droplet.networks.v4[0].ip_address }}"
        dest: ./droplet_ip.txt // bla mdirha , ghi fri3 ras 7it mtalbinhach
      delegate_to: localhost