---
- name: Create a DigitalOcean Droplet
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a DigitalOcean Droplet
      community.digitalocean.digital_ocean_droplet:
        name: my-new-droplet
        state: present
        api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"  # Use the environment variable
        size: s-1vcpu-1gb
        image: ubuntu-20-04-x64
        region: nyc1
        ssh_keys:
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDzjrZemyJHcAlXsfDztroOa4tTsv6F2b+o77KdNkkMiEyYbn8Pn4kxcWT298uucoDFAUWVL307Om3vr5BDiOZONCPro8/vBY2WfQ+IyXpB+W5HiRQ2e2vCJzdQq3J97serCcwAwTIOiN7QpmXLj6g+tIRuuqqUSi5z+vA/qOIxVWjTGkjcyMSNEp2MzJjZmOD4j9/6a9o2Urtu4Wpt1f1rvC4Y3lnyFw8nygXpU6SN/9Z2b0euLNIBrStuV9QdoQvaZ7+MpSep+cxrcVAWP6ADDEnvKMk9/O28UsItACrvrWdCPVGOblohnfspO+iL874NvrPkjXKDPTQeQCsdL9O2UU/20JrIjnLHYR9Oi2QT/23TAz47NRhLk7Vb14i2Aqq/bFG6BO1p7XJww1HB9Ju1vIs+YJwDMjFRbYKy2ZO5GQG36qsnt6d5bsxujBVG2gLmD16B2Ep7PsenOL6nNOQfgeKOPS2qDBLUYEO6YcFH24ZkcL6Zvuv1zMUZdgYAa4U= rgatnaou@e2r4p5.1337.ma"
        tags:
          - "web"
        wait: yes

