services:
    mariadb:
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        port:
            - "3306:3306"
        volumes:
            - mariadb:/var/lib/mysql
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
        env_file:
            - .env
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/html:/usr/share/nginx/html
        depends_on:
            - mariadb
    wordpress:
        build:
            context: ./wordpress
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:80"
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/html
        depends_on:
            - mariadb

volumes:
    mariadb:
    wordpress: